# Generated by Django 2.2.4 on 2020-03-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conversion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFeed',
        ),
    ]
